build:
	bibtex2html -nodoc -nobibsource \
	-footer "see [bibtex](static/publications/zwl_bib.html)" \
	zwl.bib
#	cat publications-header.md > _publications.md
#	cat zwl.html >> _publications.md
#	cp _publications.md ../web/content/about/publications.md
	cat publications-header.md  zwl.html > ../web/content/about/publications.md
